
CREATE DATABASE ESCOLA;

CREATE TABLE USUARIO(
    USU_NOME VARCHAR(45) NOT NULL,
    USU_CODIGO INT PRIMARY KEY,
    USU_SENHA VARCHAR(15) NOT NULL
    USU_EMAIL VARCHAR(25) NOT NULL UNIQUE (email LIKE '%@gmail.com'),

);

CREATE TABLE REDACAO(
    RED_TEMA VARCHAR(10) NOT NULL,
    RED_CODIGO INT PRIMARY KEY,
    RED_TEXTO VARCHAR(500) NOT NULL,
    RED_USU_CODIGO INT,
    FOREIGN KEY (RED_USU_CODIGO),
    REFERENCES USUARIO(USU_CODIGO),
);