
CREATE DATABASE ESCOLA;

USE escola;

CREATE TABLE USUARIO(
    USU_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(150) NOT NULL,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_EMAIL VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE REDACAO(
    RED_TEMA VARCHAR(10) NOT NULL,
    RED_CODIGO INT PRIMARY KEY,
    RED_TEXTO VARCHAR(500) NOT NULL,
    RED_USU_CODIGO INT,
    FOREIGN KEY (RED_USU_CODIGO)
    REFERENCES USUARIO(USU_CODIGO)
);