CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE USUARIO(

    USU_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(150) NOT NULL,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_EMAIL VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE REDACAO(

    RED_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    RED_TEMA VARCHAR(255) NOT NULL,
    RED_INTRODUCAO TEXT NOT NULL,
    RED_DESENVOLVIMENTO TEXT NOT NULL,
    RED_CONCLUSAO TEXT NOT NULL,
    RED_USU_CODIGO INT,
    
    FOREIGN KEY (RED_USU_CODIGO)
    REFERENCES USUARIO(USU_CODIGO)
);
CREATE TABLE CORRECAO(

    COR_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    COR_RED_CODIGO INT,
    COR_NOTA INT,
    COR_TEXTO TEXT,

    FOREIGN KEY (COR_RED_CODIGO)
    REFERENCES REDACAO(RED_CODIGO)

);